version: '3.9'
services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod-image
    image: application:latest
    hostname: application
    restart: always
    environment:
      AzureAd__ClientId: $AZURE_CLIENT_ID
      AzureAd__TenantId: $AZURE_TENANT_ID
    ports:
      - "127.0.0.1:8080:8080"
