# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Test & Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  API_URL: "localhost:8080"

jobs:
  build-service:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - run: corepack enable

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Restore tool dependencies
      working-directory: ./service/DNE.Todo.API
      run: dotnet tool restore

    - name: Test
      run: dotnet test --verbosity normal

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    - name: Upload Open API Definiton
      uses: actions/upload-artifact@v3
      with:
        name: openapi.json
        path: ./service/DNE.Todo.API/bin/Release/net8.0/openapi.json

    - name: Upload .NET artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-artifacts
        path: ./publish
      
  build-client:
    needs: build-service
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download Open API artifacts for generating the api types
      uses: actions/download-artifact@v3
      with:
        name: openapi.json
        path: ./openapi.json


    - run: corepack enable

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20.x

    - name: Restore dependencies
      working-directory: ./client
      run: yarn install --immutable

    - name: Generate API
      working-directory: ./client
      run: yarn api:generate ../openapi.json   

    - name: Generate Router
      working-directory: ./client
      run: yarn router:generate

    - name: Check lint
      working-directory: ./client
      run: yarn lint

    - name: Build
      working-directory: ./client
      run: yarn build
