# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Test & Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-service:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Restore tool dependencies
      working-directory: ./service/DNE.Todo.API
      run: dotnet tool restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    - name: Upload .NET artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-artifacts
        path: ./publish
      
  build-client:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download .NET build artifacts for generating the api types
      uses: actions/download-artifact@v3
      with:
        name: dotnet-artifacts
        path: ./dotnet-artifacts

    - run: corepack enable

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20.x

    - name: Restore dependencies
      working-directory: ./client
      run: yarn install --immutable

    - name: Generate API
      working-directory: ./client
      run: yarn generate-api ../dotnet-artifacts/openapi.json

    - name: Check lint
      working-directory: ./client
      run: yarn lint

    - name: Build
      working-directory: ./client
      run: yarn build
